"""supplier pipeline foundation

Revision ID: b8c4bdfd5754
Revises: a6b7c8d9e0f1
Create Date: 2026-07-29 01:43:55.419708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8c4bdfd5754'
down_revision: Union[str, Sequence[str], None] = 'a6b7c8d9e0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE SEQUENCE supplier_source_artifact_code_seq "
        "START WITH 1 INCREMENT BY 1"
    )
    op.execute(
        "CREATE SEQUENCE supplier_source_pipeline_code_seq "
        "START WITH 1 INCREMENT BY 1"
    )
    op.create_table('supplier_source_artifacts',
    sa.Column('source_connection_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_code', sa.String(length=50), server_default=sa.text("'ART-' || lpad(nextval('supplier_source_artifact_code_seq'::regclass)::text, 8, '0')"), nullable=False),
    sa.Column('storage_reference', sa.String(length=1000), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('detected_format', sa.String(length=16), nullable=False),
    sa.Column('encoding', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('retention_status', sa.String(length=16), server_default='ONLINE', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("detected_format IN ('CSV','XLSX','XML','JSON')", name=op.f('ck_supplier_source_artifacts_format_valid')),
    sa.CheckConstraint("retention_status IN ('ONLINE','ARCHIVED')", name=op.f('ck_supplier_source_artifacts_retention_status_valid')),
    sa.CheckConstraint('record_count IS NULL OR record_count >= 0', name=op.f('ck_supplier_source_artifacts_record_count_nonnegative')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_supplier_source_artifacts_size_nonnegative')),
    sa.ForeignKeyConstraint(['source_connection_id'], ['supplier_sources.id'], name=op.f('fk_supplier_source_artifacts_source_connection_id_supplier_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_source_artifacts')),
    sa.UniqueConstraint('artifact_code', name='uq_supplier_source_artifacts_artifact_code'),
    sa.UniqueConstraint('storage_reference', name='uq_supplier_source_artifacts_storage_reference')
    )
    op.create_index('ix_supplier_source_artifacts_source_checksum', 'supplier_source_artifacts', ['source_connection_id', 'checksum_sha256'], unique=False)
    op.create_index('ix_supplier_source_artifacts_source_created', 'supplier_source_artifacts', ['source_connection_id', 'created_at', 'id'], unique=False)
    op.create_table('supplier_source_schedules',
    sa.Column('source_connection_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='MANUAL', nullable=False),
    sa.Column('schedule_type', sa.String(length=24), nullable=True),
    sa.Column('timezone', sa.String(length=100), server_default='Europe/Belgrade', nullable=False),
    sa.Column('schedule_configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('automation_depth', sa.String(length=32), server_default='FETCH_ONLY', nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.String(length=32), nullable=True),
    sa.Column('last_duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), server_default='300', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("automation_depth IN ('FETCH_ONLY','FETCH_AND_ANALYZE','FULL_PIPELINE')", name=op.f('ck_supplier_source_schedules_automation_depth_valid')),
    sa.CheckConstraint("schedule_type IS NULL OR schedule_type IN ('DAILY','MULTI_DAILY','INTERVAL','WEEKDAYS','WEEKLY')", name=op.f('ck_supplier_source_schedules_schedule_type_valid')),
    sa.CheckConstraint("status IN ('MANUAL','ENABLED','PAUSED')", name=op.f('ck_supplier_source_schedules_status_valid')),
    sa.CheckConstraint('consecutive_failures >= 0', name=op.f('ck_supplier_source_schedules_failures_nonnegative')),
    sa.CheckConstraint('last_duration_ms IS NULL OR last_duration_ms >= 0', name=op.f('ck_supplier_source_schedules_duration_nonnegative')),
    sa.CheckConstraint('max_attempts BETWEEN 1 AND 20', name=op.f('ck_supplier_source_schedules_attempts_valid')),
    sa.CheckConstraint('timeout_seconds BETWEEN 1 AND 86400', name=op.f('ck_supplier_source_schedules_timeout_valid')),
    sa.ForeignKeyConstraint(['source_connection_id'], ['supplier_sources.id'], name=op.f('fk_supplier_source_schedules_source_connection_id_supplier_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_source_schedules')),
    sa.UniqueConstraint('source_connection_id', name='uq_supplier_source_schedules_source_connection_id')
    )
    op.create_index('ix_supplier_source_schedules_due', 'supplier_source_schedules', ['status', 'next_run_at'], unique=False, postgresql_where=sa.text("status = 'ENABLED'"))
    op.create_table('supplier_source_pipeline_runs',
    sa.Column('source_connection_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('pipeline_code', sa.String(length=50), server_default=sa.text("'PIP-' || lpad(nextval('supplier_source_pipeline_code_seq'::regclass)::text, 8, '0')"), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('automation_depth', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('current_phase', sa.String(length=32), server_default='FETCH', nullable=False),
    sa.Column('phase_results', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('active_schema_profile_id', sa.Uuid(), nullable=True),
    sa.Column('analyzed_schema_profile_id', sa.Uuid(), nullable=True),
    sa.Column('active_mapping_profile_id', sa.Uuid(), nullable=True),
    sa.Column('acquisition_run_id', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('schedule_occurrence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=120), nullable=True),
    sa.Column('failure_message', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("automation_depth IN ('FETCH_ONLY','FETCH_AND_ANALYZE','FULL_PIPELINE')", name=op.f('ck_supplier_source_pipeline_runs_automation_depth_valid')),
    sa.CheckConstraint("current_phase IN ('FETCH','ARTIFACT_SAVE','TECHNICAL_VALIDATE','SCHEMA_ANALYZE','SCHEMA_COMPARE','MAPPING','BUSINESS_VALIDATE','STAGING','COMMIT','SNAPSHOT','DELTA','INCIDENT')", name=op.f('ck_supplier_source_pipeline_runs_phase_valid')),
    sa.CheckConstraint("status IN ('PENDING','RUNNING','SUCCEEDED','FAILED','SKIPPED','CANCELLED')", name=op.f('ck_supplier_source_pipeline_runs_status_valid')),
    sa.CheckConstraint("trigger_type IN ('MANUAL','SCHEDULED')", name=op.f('ck_supplier_source_pipeline_runs_trigger_type_valid')),
    sa.ForeignKeyConstraint(['acquisition_run_id'], ['supplier_acquisition_runs.id'], name=op.f('fk_supplier_source_pipeline_runs_acquisition_run_id_supplier_acquisition_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['active_mapping_profile_id'], ['supplier_mapping_profiles.id'], name=op.f('fk_supplier_source_pipeline_runs_active_mapping_profile_id_supplier_mapping_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['active_schema_profile_id'], ['supplier_schema_profiles.id'], name=op.f('fk_supplier_source_pipeline_runs_active_schema_profile_id_supplier_schema_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['analyzed_schema_profile_id'], ['supplier_schema_profiles.id'], name=op.f('fk_supplier_source_pipeline_runs_analyzed_schema_profile_id_supplier_schema_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['artifact_id'], ['supplier_source_artifacts.id'], name=op.f('fk_supplier_source_pipeline_runs_artifact_id_supplier_source_artifacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_supplier_source_pipeline_runs_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['supplier_source_schedules.id'], name=op.f('fk_supplier_source_pipeline_runs_schedule_id_supplier_source_schedules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_connection_id'], ['supplier_sources.id'], name=op.f('fk_supplier_source_pipeline_runs_source_connection_id_supplier_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_source_pipeline_runs')),
    sa.UniqueConstraint('idempotency_key', name='uq_supplier_source_pipeline_runs_idempotency_key'),
    sa.UniqueConstraint('job_id', name='uq_supplier_source_pipeline_runs_job_id'),
    sa.UniqueConstraint('pipeline_code', name='uq_supplier_source_pipeline_runs_pipeline_code')
    )
    op.create_index('ix_supplier_source_pipeline_runs_schedule_occurrence', 'supplier_source_pipeline_runs', ['schedule_id', 'schedule_occurrence_at'], unique=False)
    op.create_index('uq_supplier_source_pipeline_runs_schedule_occurrence', 'supplier_source_pipeline_runs', ['schedule_id', 'schedule_occurrence_at'], unique=True, postgresql_where=sa.text("schedule_id IS NOT NULL"))
    op.create_index('ix_supplier_source_pipeline_runs_source_created', 'supplier_source_pipeline_runs', ['source_connection_id', 'created_at', 'id'], unique=False)
    op.create_index('uq_supplier_source_pipeline_runs_source_active', 'supplier_source_pipeline_runs', ['source_connection_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING','RUNNING')"))
    op.create_table('supplier_schema_compatibility_reports',
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('active_schema_profile_id', sa.Uuid(), nullable=False),
    sa.Column('analyzed_schema_profile_id', sa.Uuid(), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("result IN ('COMPATIBLE','COMPATIBLE_WITH_WARNINGS','INCOMPATIBLE')", name=op.f('ck_supplier_schema_compatibility_reports_result_valid')),
    sa.CheckConstraint("severity IN ('INFO','WARNING','ERROR','CRITICAL')", name=op.f('ck_supplier_schema_compatibility_reports_severity_valid')),
    sa.ForeignKeyConstraint(['active_schema_profile_id'], ['supplier_schema_profiles.id'], name=op.f('fk_supplier_schema_compatibility_reports_active_schema_profile_id_supplier_schema_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['analyzed_schema_profile_id'], ['supplier_schema_profiles.id'], name=op.f('fk_supplier_schema_compatibility_reports_analyzed_schema_profile_id_supplier_schema_profiles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['artifact_id'], ['supplier_source_artifacts.id'], name=op.f('fk_supplier_schema_compatibility_reports_artifact_id_supplier_source_artifacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['supplier_source_pipeline_runs.id'], name=op.f('fk_supplier_schema_compatibility_reports_pipeline_run_id_supplier_source_pipeline_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_schema_compatibility_reports')),
    sa.UniqueConstraint('pipeline_run_id', name='uq_supplier_schema_compatibility_reports_pipeline_run_id')
    )
    op.create_index('ix_supplier_schema_compatibility_reports_active_schema_created', 'supplier_schema_compatibility_reports', ['active_schema_profile_id', 'created_at'], unique=False)
    op.add_column('supplier_schema_profiles', sa.Column('detected_format', sa.String(length=16), nullable=True))
    op.add_column('supplier_schema_profiles', sa.Column('encoding', sa.String(length=100), nullable=True))
    op.add_column('supplier_schema_profiles', sa.Column('delimiter', sa.String(length=10), nullable=True))
    op.add_column('supplier_schema_profiles', sa.Column('root_path', sa.String(length=500), nullable=True))
    op.add_column('supplier_schema_profiles', sa.Column('record_path', sa.String(length=500), nullable=True))
    op.add_column('supplier_schema_profiles', sa.Column('baseline_artifact_id', sa.Uuid(), nullable=True))
    op.add_column('supplier_schema_profiles', sa.Column('baseline_checksum', sa.String(length=64), nullable=True))
    op.add_column('supplier_schema_profiles', sa.Column('baseline_record_count', sa.Integer(), nullable=True))
    op.add_column('supplier_schema_profiles', sa.Column('compatibility_policy', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('supplier_schema_profiles', sa.Column('analysis_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('supplier_schema_profiles', sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(op.f('fk_supplier_schema_profiles_baseline_artifact_id_supplier_source_artifacts'), 'supplier_schema_profiles', 'supplier_source_artifacts', ['baseline_artifact_id'], ['id'], ondelete='RESTRICT')
    op.add_column('supplier_snapshots', sa.Column('pipeline_run_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(op.f('uq_supplier_snapshots_pipeline_run_id'), 'supplier_snapshots', ['pipeline_run_id'])
    op.create_foreign_key(op.f('fk_supplier_snapshots_pipeline_run_id_supplier_source_pipeline_runs'), 'supplier_snapshots', 'supplier_source_pipeline_runs', ['pipeline_run_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_supplier_snapshots_pipeline_run_id_supplier_source_pipeline_runs'), 'supplier_snapshots', type_='foreignkey')
    op.drop_constraint(op.f('uq_supplier_snapshots_pipeline_run_id'), 'supplier_snapshots', type_='unique')
    op.drop_column('supplier_snapshots', 'pipeline_run_id')
    op.drop_constraint(op.f('fk_supplier_schema_profiles_baseline_artifact_id_supplier_source_artifacts'), 'supplier_schema_profiles', type_='foreignkey')
    op.drop_column('supplier_schema_profiles', 'last_analyzed_at')
    op.drop_column('supplier_schema_profiles', 'analysis_metadata')
    op.drop_column('supplier_schema_profiles', 'compatibility_policy')
    op.drop_column('supplier_schema_profiles', 'baseline_record_count')
    op.drop_column('supplier_schema_profiles', 'baseline_checksum')
    op.drop_column('supplier_schema_profiles', 'baseline_artifact_id')
    op.drop_column('supplier_schema_profiles', 'record_path')
    op.drop_column('supplier_schema_profiles', 'root_path')
    op.drop_column('supplier_schema_profiles', 'delimiter')
    op.drop_column('supplier_schema_profiles', 'encoding')
    op.drop_column('supplier_schema_profiles', 'detected_format')
    op.drop_index('ix_supplier_schema_compatibility_reports_active_schema_created', table_name='supplier_schema_compatibility_reports')
    op.drop_table('supplier_schema_compatibility_reports')
    op.drop_index('uq_supplier_source_pipeline_runs_source_active', table_name='supplier_source_pipeline_runs', postgresql_where=sa.text("status IN ('PENDING','RUNNING')"))
    op.drop_index('uq_supplier_source_pipeline_runs_schedule_occurrence', table_name='supplier_source_pipeline_runs', postgresql_where=sa.text("schedule_id IS NOT NULL"))
    op.drop_index('ix_supplier_source_pipeline_runs_source_created', table_name='supplier_source_pipeline_runs')
    op.drop_index('ix_supplier_source_pipeline_runs_schedule_occurrence', table_name='supplier_source_pipeline_runs')
    op.drop_table('supplier_source_pipeline_runs')
    op.drop_index('ix_supplier_source_schedules_due', table_name='supplier_source_schedules', postgresql_where=sa.text("status = 'ENABLED'"))
    op.drop_table('supplier_source_schedules')
    op.drop_index('ix_supplier_source_artifacts_source_created', table_name='supplier_source_artifacts')
    op.drop_index('ix_supplier_source_artifacts_source_checksum', table_name='supplier_source_artifacts')
    op.drop_table('supplier_source_artifacts')
    op.execute("DROP SEQUENCE supplier_source_pipeline_code_seq")
    op.execute("DROP SEQUENCE supplier_source_artifact_code_seq")
    # ### end Alembic commands ###
