"""add products table

Revision ID: eb5f2829e72e
Revises: d4a9c8e7f621
Create Date: 2026-07-22 22:33:38.134275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb5f2829e72e'
down_revision: Union[str, Sequence[str], None] = 'd4a9c8e7f621'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('ean', sa.String(length=32), nullable=True),
    sa.Column('mpn', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('manufacturer', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('code', name='uq_products_code'),
    sa.UniqueConstraint('ean', name='uq_products_ean'),
    sa.UniqueConstraint('sku', name='uq_products_sku')
    )
    op.create_index('ix_products_active', 'products', ['is_active'], unique=False)
    op.create_index('ix_products_brand', 'products', ['brand'], unique=False)
    op.create_index('ix_products_category', 'products', ['category_id'], unique=False)
    op.create_index('ix_products_status', 'products', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_status', table_name='products')
    op.drop_index('ix_products_category', table_name='products')
    op.drop_index('ix_products_brand', table_name='products')
    op.drop_index('ix_products_active', table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
