import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Alert, Box, Button, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { supplierApi } from "../api/supplierApi";
import { PageHeader } from "../components/PageHeader";
import { StatusChip } from "../components/StatusChip";
import type { ApiError, SupplierCurrencySetting } from "../types";

const statusLabels = { CURRENT: "Ispravno", STALE: "Kurs je zastareo", MISSING: "Nedostaje kurs" } as const;
const modeLabels = { FIXED: "Fiksni", MANUAL: "Ručni unos", AUTOMATIC: "Automatski" } as const;
const sourceLabels = { CONFIGURED: "Valuta iz podešavanja", PRICE_LIST: "Valuta iz cenovnika" } as const;

export function SupplierCurrenciesPage() {
  const queryClient = useQueryClient();
  const [selected, setSelected] = useState<SupplierCurrencySetting | null>(null);
  const [settingOpen, setSettingOpen] = useState(false);
  const [rateOpen, setRateOpen] = useState(false);
  const [supplierId, setSupplierId] = useState("");
  const [currency, setCurrency] = useState("RSD");
  const [currencySource, setCurrencySource] = useState<"CONFIGURED" | "PRICE_LIST">("CONFIGURED");
  const [rateMode, setRateMode] = useState<"FIXED" | "MANUAL" | "AUTOMATIC">("FIXED");
  const [automaticUrl, setAutomaticUrl] = useState("");
  const [rate, setRate] = useState("");
  const [note, setNote] = useState("");
  const settings = useQuery({ queryKey: ["supplier-currencies"], queryFn: supplierApi.currencySettings });
  const monitor = useQuery({ queryKey: ["monitor-currency"], queryFn: supplierApi.monitorCurrency });
  const suppliers = useQuery({ queryKey: ["currency-suppliers"], queryFn: () => supplierApi.suppliers({ limit: 500, offset: 0 }) });
  const rates = useQuery({ queryKey: ["supplier-exchange-rates", selected?.supplier_id], queryFn: () => supplierApi.exchangeRates(selected!.supplier_id), enabled: Boolean(selected) });
  const configured = useMemo(() => new Set((settings.data?.items ?? []).map((item) => item.supplier_id)), [settings.data]);
  const saveSetting = useMutation({ mutationFn: () => supplierApi.saveCurrencySetting(supplierId, { currency_code: currency, currency_source: currencySource, rate_mode: rateMode, automatic_source_url: rateMode === "AUTOMATIC" ? automaticUrl : null, max_rate_age_hours: 48, expected_version: selected?.supplier_id === supplierId ? selected.version : null }), onSuccess: async () => { setSettingOpen(false); setSelected(null); await queryClient.invalidateQueries({ queryKey: ["supplier-currencies"] }); } });
  const saveRate = useMutation({ mutationFn: () => supplierApi.addExchangeRate(selected!.supplier_id, { rate_to_rsd: rate, effective_at: new Date().toISOString(), source_type: selected!.rate_mode, note }), onSuccess: async () => { setRateOpen(false); setRate(""); setNote(""); await queryClient.invalidateQueries({ queryKey: ["supplier-currencies"] }); await queryClient.invalidateQueries({ queryKey: ["supplier-exchange-rates"] }); } });
  const openNew = () => { setSelected(null); setSupplierId(""); setCurrency("RSD"); setCurrencySource("CONFIGURED"); setRateMode("FIXED"); setAutomaticUrl(""); setSettingOpen(true); };
  const openEdit = (row: SupplierCurrencySetting) => { setSelected(row); setSupplierId(row.supplier_id); setCurrency(row.currency_code); setCurrencySource(row.currency_source); setRateMode(row.rate_mode); setAutomaticUrl(row.automatic_source_url ?? ""); setSettingOpen(true); };
  const error = (settings.error || saveSetting.error || saveRate.error) as ApiError | null;
  return <Box>
    <PageHeader title="Valute dobavljača" description="Osnovna valuta Monitora je RSD sa kursom 1. Dobavljačke cene se zaključavaju uz kurs korišćen za konkretan cenovnik." actions={<Button variant="contained" onClick={openNew}>Dodaj podešavanje</Button>} />
    <Stack direction={{ xs: "column", sm: "row" }} gap={2} mb={2}><Paper sx={{ p: 2, minWidth: 220 }}><Typography color="text.secondary">Monitor valuta</Typography><Typography variant="h2">{monitor.data?.currency_code ?? "RSD"} = {monitor.data?.rate_to_rsd ?? "1"}</Typography></Paper><Paper sx={{ p: 2, minWidth: 220 }}><Typography color="text.secondary">Podešeni dobavljači</Typography><Typography variant="h2">{settings.data?.total ?? 0}</Typography></Paper></Stack>
    {error && <Alert severity="error" sx={{ mb: 2 }}>{error.message}</Alert>}
    <TableContainer component={Paper}><Table><TableHead><TableRow><TableCell>Dobavljač</TableCell><TableCell>Valuta</TableCell><TableCell align="right">Kurs u RSD</TableCell><TableCell>Važi od</TableCell><TableCell>Način</TableCell><TableCell>Status</TableCell><TableCell /></TableRow></TableHead><TableBody>
      {(settings.data?.items ?? []).map((row) => <TableRow key={row.id} hover selected={selected?.id === row.id} onClick={() => setSelected(row)} sx={{ cursor: "pointer" }}><TableCell>{row.supplier_name}</TableCell><TableCell>{row.currency_code}</TableCell><TableCell align="right">{row.current_rate ?? "—"}</TableCell><TableCell>{row.current_rate_effective_at ? new Date(row.current_rate_effective_at).toLocaleString("sr-RS") : "—"}</TableCell><TableCell>{modeLabels[row.rate_mode]}</TableCell><TableCell><StatusChip value={row.rate_status} label={statusLabels[row.rate_status]} /></TableCell><TableCell><Button onClick={(event) => { event.stopPropagation(); openEdit(row); }}>Izmeni</Button></TableCell></TableRow>)}
      {!settings.isLoading && settings.data?.items.length === 0 && <TableRow><TableCell colSpan={7}>Nijedan dobavljač još nema podešenu valutu.</TableCell></TableRow>}
    </TableBody></Table></TableContainer>
    {selected && <Paper sx={{ p: 2, mt: 2 }}><Stack direction={{ xs: "column", md: "row" }} justifyContent="space-between" gap={2}><Box><Typography variant="h3">{selected.supplier_name} — istorija kursa</Typography><Typography color="text.secondary">{sourceLabels[selected.currency_source]}</Typography></Box>{selected.currency_code !== "RSD" && selected.rate_mode !== "AUTOMATIC" && <Button variant="contained" onClick={() => setRateOpen(true)}>Dodaj kurs</Button>}</Stack>{selected.rate_mode === "AUTOMATIC" && <Alert severity="info" sx={{ mt: 2 }}>Automatski kurs upisuje isključivo interni servis uz dokaz o preuzetom izvoru.</Alert>}<Table size="small"><TableHead><TableRow><TableCell>Datum važenja</TableCell><TableCell align="right">Kurs</TableCell><TableCell>Izvor</TableCell><TableCell>Napomena</TableCell></TableRow></TableHead><TableBody>{(rates.data ?? []).map((item) => <TableRow key={item.id}><TableCell>{new Date(item.effective_at).toLocaleString("sr-RS")}</TableCell><TableCell align="right">{item.rate_to_rsd}</TableCell><TableCell>{modeLabels[item.source_type as keyof typeof modeLabels] ?? item.source_type}</TableCell><TableCell>{item.note ?? "—"}</TableCell></TableRow>)}</TableBody></Table></Paper>}
    <Dialog open={settingOpen} onClose={() => setSettingOpen(false)} fullWidth><DialogTitle>Podešavanje valute dobavljača</DialogTitle><DialogContent><Stack gap={2} mt={1}><FormControl><InputLabel>Dobavljač</InputLabel><Select value={supplierId} label="Dobavljač" disabled={Boolean(selected)} onChange={(e) => setSupplierId(e.target.value)}>{(suppliers.data?.items ?? []).filter((s) => selected?.supplier_id === s.id || !configured.has(s.id)).map((s) => <MenuItem key={s.id} value={s.id}>{s.company_name}</MenuItem>)}</Select></FormControl><TextField label="ISO valuta" value={currency} inputProps={{ maxLength: 3 }} onChange={(e) => { const value = e.target.value.toUpperCase(); setCurrency(value); if (value === "RSD") setRateMode("FIXED"); }} /><FormControl><InputLabel>Odakle dolazi valuta</InputLabel><Select value={currencySource} label="Odakle dolazi valuta" onChange={(e) => setCurrencySource(e.target.value as typeof currencySource)}><MenuItem value="CONFIGURED">Iz podešavanja</MenuItem><MenuItem value="PRICE_LIST">Obavezna u cenovniku</MenuItem></Select></FormControl><FormControl><InputLabel>Način kursa</InputLabel><Select value={rateMode} label="Način kursa" disabled={currency === "RSD"} onChange={(e) => setRateMode(e.target.value as typeof rateMode)}><MenuItem value="FIXED">Fiksni</MenuItem><MenuItem value="MANUAL">Ručni unos</MenuItem><MenuItem value="AUTOMATIC">Automatski</MenuItem></Select></FormControl>{rateMode === "AUTOMATIC" && <TextField label="HTTPS adresa izvora kursa" value={automaticUrl} onChange={(e) => setAutomaticUrl(e.target.value)} />}</Stack></DialogContent><DialogActions><Button onClick={() => setSettingOpen(false)}>Otkaži</Button><Button variant="contained" disabled={!supplierId || currency.length !== 3 || saveSetting.isPending} onClick={() => saveSetting.mutate()}>Sačuvaj</Button></DialogActions></Dialog>
    <Dialog open={rateOpen} onClose={() => setRateOpen(false)} fullWidth><DialogTitle>Dodaj kurs za {selected?.supplier_name}</DialogTitle><DialogContent><Stack gap={2} mt={1}><TextField label="Kurs prema RSD" value={rate} onChange={(e) => setRate(e.target.value.replace(",", "."))} /><TextField label="Obrazloženje / izvor" multiline minRows={3} value={note} onChange={(e) => setNote(e.target.value)} /></Stack></DialogContent><DialogActions><Button onClick={() => setRateOpen(false)}>Otkaži</Button><Button variant="contained" disabled={!rate || note.trim().length < 3 || saveRate.isPending} onClick={() => saveRate.mutate()}>Sačuvaj kurs</Button></DialogActions></Dialog>
  </Box>;
}
