from enum import StrEnum


class SupplierStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    SUSPENDED = "SUSPENDED"


class SupplierContactType(StrEnum):
    GENERAL = "GENERAL"
    TECHNICAL = "TECHNICAL"
    COMMERCIAL = "COMMERCIAL"
    BILLING = "BILLING"
    OTHER = "OTHER"


class SupplierSourceType(StrEnum):
    API = "API"
    CSV = "CSV"
    EXCEL = "EXCEL"
    XML = "XML"
    FTP = "FTP"
    SFTP = "SFTP"
    HTTP = "HTTP"
    GOOGLE_DRIVE = "GOOGLE_DRIVE"
    EMAIL = "EMAIL"
    MANUAL_UPLOAD = "MANUAL_UPLOAD"


class SupplierSourceStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    ERROR = "ERROR"


class SupplierSourceValidationStatus(StrEnum):
    VALID = "VALID"
    INVALID = "INVALID"


class SchemaProfileStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class SchemaFieldDataType(StrEnum):
    STRING = "STRING"
    INTEGER = "INTEGER"
    DECIMAL = "DECIMAL"
    BOOLEAN = "BOOLEAN"
    DATE = "DATE"
    DATETIME = "DATETIME"
    TIME = "TIME"
    UUID = "UUID"
    EMAIL = "EMAIL"
    URL = "URL"
    PHONE = "PHONE"
    JSON = "JSON"
    ENUM = "ENUM"
    BINARY = "BINARY"


class MappingProfileStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    ARCHIVED = "ARCHIVED"


class MappingTransformationType(StrEnum):
    NONE = "NONE"
    COPY = "COPY"
    DEFAULT_VALUE = "DEFAULT_VALUE"
    CONSTANT = "CONSTANT"
    CONCAT = "CONCAT"
    SPLIT = "SPLIT"
    TRIM = "TRIM"
    UPPERCASE = "UPPERCASE"
    LOWERCASE = "LOWERCASE"
    REPLACE = "REPLACE"
    REGEX = "REGEX"


class AcquisitionTriggerType(StrEnum):
    MANUAL = "MANUAL"
    API_REQUEST = "API_REQUEST"
    MANUAL_UPLOAD = "MANUAL_UPLOAD"


class AcquisitionStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    PARTIALLY_SUCCEEDED = "PARTIALLY_SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class AcquisitionRecordStatus(StrEnum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class AcquisitionIssueSeverity(StrEnum):
    WARNING = "WARNING"
    ERROR = "ERROR"


class SnapshotStatus(StrEnum):
    BUILDING = "BUILDING"
    READY = "READY"
    FAILED = "FAILED"


class SnapshotStorageState(StrEnum):
    ONLINE = "ONLINE"
    ARCHIVED = "ARCHIVED"
    RESTORING = "RESTORING"


class SnapshotArchiveStatus(StrEnum):
    EXPORTING = "EXPORTING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    OFFLOADED = "OFFLOADED"
    RESTORED = "RESTORED"


class DeltaStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class DeltaChangeType(StrEnum):
    ADDED = "ADDED"
    REMOVED = "REMOVED"
    MODIFIED = "MODIFIED"


class DeltaFieldChangeType(StrEnum):
    VALUE_CHANGED = "VALUE_CHANGED"
    VALUE_ADDED = "VALUE_ADDED"
    VALUE_REMOVED = "VALUE_REMOVED"
    TYPE_CHANGED = "TYPE_CHANGED"
    ARRAY_CHANGED = "ARRAY_CHANGED"


class IncidentSourceDomain(StrEnum):
    ACQUISITION = "ACQUISITION"
    SNAPSHOT = "SNAPSHOT"
    DELTA = "DELTA"
    SOURCE_CONNECTION = "SOURCE_CONNECTION"
    SCHEMA = "SCHEMA"
    MAPPING = "MAPPING"
    MANUAL = "MANUAL"
    SYSTEM = "SYSTEM"


class IncidentPriority(StrEnum):
    P4 = "P4"
    P3 = "P3"
    P2 = "P2"
    P1 = "P1"


class IncidentType(StrEnum):
    ACQUISITION_FAILED = "ACQUISITION_FAILED"
    ACQUISITION_CANCELLED_UNEXPECTEDLY = "ACQUISITION_CANCELLED_UNEXPECTEDLY"
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    SOURCE_AUTHENTICATION_FAILED = "SOURCE_AUTHENTICATION_FAILED"
    SECRET_RESOLUTION_FAILED = "SECRET_RESOLUTION_FAILED"
    UNSUPPORTED_SOURCE_EXECUTION = "UNSUPPORTED_SOURCE_EXECUTION"
    MALFORMED_SOURCE_FILE = "MALFORMED_SOURCE_FILE"
    UNSUPPORTED_SOURCE_FORMAT = "UNSUPPORTED_SOURCE_FORMAT"
    FILE_SIZE_LIMIT_EXCEEDED = "FILE_SIZE_LIMIT_EXCEEDED"
    RECORD_COUNT_LIMIT_EXCEEDED = "RECORD_COUNT_LIMIT_EXCEEDED"
    HIGH_REJECTED_ROW_COUNT = "HIGH_REJECTED_ROW_COUNT"
    HIGH_REJECTED_ROW_RATIO = "HIGH_REJECTED_ROW_RATIO"
    REQUIRED_FIELD_FAILURE = "REQUIRED_FIELD_FAILURE"
    MAPPING_EXECUTION_FAILURE = "MAPPING_EXECUTION_FAILURE"
    DUPLICATE_SOURCE_IDENTITY = "DUPLICATE_SOURCE_IDENTITY"
    SNAPSHOT_BUILD_FAILED = "SNAPSHOT_BUILD_FAILED"
    SNAPSHOT_INTEGRITY_FAILURE = "SNAPSHOT_INTEGRITY_FAILURE"
    SNAPSHOT_ARCHIVE_FAILED = "SNAPSHOT_ARCHIVE_FAILED"
    SNAPSHOT_ARCHIVE_CORRUPTED = "SNAPSHOT_ARCHIVE_CORRUPTED"
    SNAPSHOT_OFFLOAD_FAILED = "SNAPSHOT_OFFLOAD_FAILED"
    SNAPSHOT_RESTORE_FAILED = "SNAPSHOT_RESTORE_FAILED"
    SNAPSHOT_RESTORATION_REQUIRED = "SNAPSHOT_RESTORATION_REQUIRED"
    SNAPSHOT_STORAGE_UNAVAILABLE = "SNAPSHOT_STORAGE_UNAVAILABLE"
    DELTA_CALCULATION_FAILED = "DELTA_CALCULATION_FAILED"
    DELTA_DUPLICATE_IDENTITY = "DELTA_DUPLICATE_IDENTITY"
    HIGH_REMOVAL_RATIO = "HIGH_REMOVAL_RATIO"
    HIGH_ADDITION_RATIO = "HIGH_ADDITION_RATIO"
    LARGE_ITEM_COUNT_DROP = "LARGE_ITEM_COUNT_DROP"
    LARGE_ITEM_COUNT_INCREASE = "LARGE_ITEM_COUNT_INCREASE"
    LARGE_PRICE_INCREASE = "LARGE_PRICE_INCREASE"
    LARGE_PRICE_DECREASE = "LARGE_PRICE_DECREASE"
    CURRENCY_CHANGED = "CURRENCY_CHANGED"
    ALL_STOCK_BECAME_UNAVAILABLE = "ALL_STOCK_BECAME_UNAVAILABLE"
    UNUSUAL_FIELD_CHANGE_VOLUME = "UNUSUAL_FIELD_CHANGE_VOLUME"
    SCHEMA_VERSION_CHANGED = "SCHEMA_VERSION_CHANGED"
    MAPPING_VERSION_CHANGED = "MAPPING_VERSION_CHANGED"
    IMAGE_SET_CHANGED = "IMAGE_SET_CHANGED"
    MANUAL_DATA_QUALITY_REPORT = "MANUAL_DATA_QUALITY_REPORT"
    MANUAL_SUPPLIER_REPORT = "MANUAL_SUPPLIER_REPORT"
    CONFIGURATION_REVIEW_REQUIRED = "CONFIGURATION_REVIEW_REQUIRED"
    OTHER = "OTHER"


__all__ = [
    "SupplierContactType",
    "SupplierSourceStatus",
    "SupplierSourceType",
    "SupplierSourceValidationStatus",
    "SupplierStatus",
]
