from __future__ import annotations

SOURCE_DOMAINS = frozenset(
    {
        "ACQUISITION",
        "SNAPSHOT",
        "DELTA",
        "SOURCE_CONNECTION",
        "SCHEMA",
        "MAPPING",
        "MANUAL",
        "SYSTEM",
    }
)
INCIDENT_TYPES = frozenset(
    {
        "ACQUISITION_FAILED",
        "ACQUISITION_CANCELLED_UNEXPECTEDLY",
        "SOURCE_UNAVAILABLE",
        "SOURCE_AUTHENTICATION_FAILED",
        "SECRET_RESOLUTION_FAILED",
        "UNSUPPORTED_SOURCE_EXECUTION",
        "MALFORMED_SOURCE_FILE",
        "UNSUPPORTED_SOURCE_FORMAT",
        "FILE_SIZE_LIMIT_EXCEEDED",
        "RECORD_COUNT_LIMIT_EXCEEDED",
        "HIGH_REJECTED_ROW_COUNT",
        "HIGH_REJECTED_ROW_RATIO",
        "REQUIRED_FIELD_FAILURE",
        "MAPPING_EXECUTION_FAILURE",
        "DUPLICATE_SOURCE_IDENTITY",
        "SNAPSHOT_BUILD_FAILED",
        "SNAPSHOT_INTEGRITY_FAILURE",
        "SNAPSHOT_ARCHIVE_FAILED",
        "SNAPSHOT_ARCHIVE_CORRUPTED",
        "SNAPSHOT_OFFLOAD_FAILED",
        "SNAPSHOT_RESTORE_FAILED",
        "SNAPSHOT_RESTORATION_REQUIRED",
        "SNAPSHOT_STORAGE_UNAVAILABLE",
        "DELTA_CALCULATION_FAILED",
        "DELTA_DUPLICATE_IDENTITY",
        "HIGH_REMOVAL_RATIO",
        "HIGH_ADDITION_RATIO",
        "LARGE_ITEM_COUNT_DROP",
        "LARGE_ITEM_COUNT_INCREASE",
        "LARGE_PRICE_INCREASE",
        "LARGE_PRICE_DECREASE",
        "CURRENCY_CHANGED",
        "ALL_STOCK_BECAME_UNAVAILABLE",
        "UNUSUAL_FIELD_CHANGE_VOLUME",
        "SCHEMA_VERSION_CHANGED",
        "MAPPING_VERSION_CHANGED",
        "IMAGE_SET_CHANGED",
        "MANUAL_DATA_QUALITY_REPORT",
        "MANUAL_SUPPLIER_REPORT",
        "CONFIGURATION_REVIEW_REQUIRED",
        "OTHER",
    }
)
SEVERITIES = ("INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL")
PRIORITIES = ("P4", "P3", "P2", "P1")
ACTIVE_STATUSES = frozenset({"OPEN", "ACKNOWLEDGED", "IN_PROGRESS", "SUPPRESSED"})
TERMINAL_STATUSES = frozenset({"RESOLVED", "DISMISSED"})
ALLOWED_TRANSITIONS = {
    "OPEN": {"ACKNOWLEDGED", "IN_PROGRESS", "RESOLVED", "DISMISSED", "SUPPRESSED"},
    "ACKNOWLEDGED": {"IN_PROGRESS", "RESOLVED", "DISMISSED", "SUPPRESSED"},
    "IN_PROGRESS": {"RESOLVED", "DISMISSED", "SUPPRESSED"},
    "RESOLVED": {"OPEN"},
    "DISMISSED": {"OPEN"},
    "SUPPRESSED": {"OPEN"},
}
DEFAULT_PRIORITY = {
    "INFO": "P4",
    "LOW": "P4",
    "MEDIUM": "P3",
    "HIGH": "P2",
    "CRITICAL": "P1",
}
DEFAULT_DUE_HOURS = {"P1": 4, "P2": 24, "P3": 72, "P4": 168}

SIGNAL_TO_INCIDENT = {
    "HIGH_REMOVAL_RATIO": "HIGH_REMOVAL_RATIO",
    "HIGH_ADDITION_RATIO": "HIGH_ADDITION_RATIO",
    "LARGE_ITEM_COUNT_DROP": "LARGE_ITEM_COUNT_DROP",
    "LARGE_ITEM_COUNT_INCREASE": "LARGE_ITEM_COUNT_INCREASE",
    "LARGE_PRICE_INCREASE": "LARGE_PRICE_INCREASE",
    "LARGE_PRICE_DECREASE": "LARGE_PRICE_DECREASE",
    "CURRENCY_CHANGED": "CURRENCY_CHANGED",
    "ALL_STOCK_BECAME_UNAVAILABLE": "ALL_STOCK_BECAME_UNAVAILABLE",
    "UNUSUAL_FIELD_CHANGE_VOLUME": "UNUSUAL_FIELD_CHANGE_VOLUME",
    "SCHEMA_VERSION_CHANGED": "SCHEMA_VERSION_CHANGED",
    "MAPPING_VERSION_CHANGED": "MAPPING_VERSION_CHANGED",
    "IMAGE_SET_CHANGED": "IMAGE_SET_CHANGED",
    "DUPLICATE_IDENTITY": "DELTA_DUPLICATE_IDENTITY",
}

__all__ = [
    "ACTIVE_STATUSES",
    "ALLOWED_TRANSITIONS",
    "DEFAULT_DUE_HOURS",
    "DEFAULT_PRIORITY",
    "INCIDENT_TYPES",
    "PRIORITIES",
    "SEVERITIES",
    "SIGNAL_TO_INCIDENT",
    "SOURCE_DOMAINS",
    "TERMINAL_STATUSES",
]
